#debug: true
#logging:
#  file: learning.log
#  level:
#    com: debug


person:
  name: cot
  age: 25
  sex: 1
  maps:
    name: m1
  pets:
    - dog
    - cat
    - pig
    - birds

#ActiveMQ
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin


